Webhook: true
DiscordWebhookURL: "https://discord.com/api/webhooks/1001889150129152150/L6a_4y0kUKtP_OJ-JO2wnP--1ZBduqdhge4EcgAkZgmF-8bevBC7hUBxF9JVvLQDalYy"

Groups:
  member:
    permission:
      - pinont.member