Webhook: true
DiscordWebhookURL: ""
AntiCheatHook: ""

deadmsg:
  - " was slain by "
  - " took the L to "
  - " got rekt by "
  - " got smacked by "
  - " got BONK by "
  - " got rip by "
  - " took an E by "
  - " was turned to dust by "
  - " was turned to ash by "
  - " was melted by "
  - " was stomped by "
  -
wc:
  16x16:
    1:
      schematic: ""
    2:
      schematic: ""
  32x16:
    1:
      schematic: ""
  32x32:
    schematic: ""
