Webhook: true
DiscordWebhookURL: "https://discord.com/api/webhooks/1001889150129152150/L6a_4y0kUKtP_OJ-JO2wnP--1ZBduqdhge4EcgAkZgmF-8bevBC7hUBxF9JVvLQDalYy"
AntiCheatHook: "https://discord.com/api/webhooks/1004005092241965058/pLvqXp0rDHVvoKfoLZGOQfX3h1Jkc6cIOMYMBxuM__1HLSZMStyY2h_3_QDoSVz2zvlA"

deadmsg:
  - " was slain by "
  - " took the L to "
  - " got rekt by "
  - " got smacked by "
  - " got BONK by "
  - " got rip by "
  - " took an E by "
  - " was turned to dust by "
  - " was turned to ash by "
  - " was melted by "
<<<<<<< HEAD
  - " was stomped by "

# Later

#WardenChunks:
#  chunk1:
#    x: 0
#    y: 0
#    z: 0
#
#  chunk2:
#    x: 0
#    y: 0
#    z: 0
=======
  - " was stomped by "
>>>>>>> 8fa805bcde8725f5a1ba696ac001f35c9ef6f392
