name: Minigame
version: '${project.version}'
main: pinont.server.minigame.Minigame
api-version: 1.19
authors: [ 'pinont' ]
description: Minigames for Pinont's Server

commands:
  spawn:
    description: go to spawn
    usage: /spawn

  kit:
    description: kit
    usage: /kit