name: 'PRAFWarPlugin'
version: '${project.version}'
main: pinont.server.minigame.Minigame
api-version: 1.19
authors: [ 'Pinont','ItDragClick' ]
description: Minigames for Pinont's Server

commands:
  spawn:
    description: go to spawn
    usage: /spawn

  gms:
    description: set gamemode 0
    usage: /gms

  gmc:
    description: set gamemode 1
    usage: /gmc

  gma:
    description: set gamemode 2
    usage: /gma

  gmsp:
    description: set gamemode 3
    usage: /gmsp

  feed:
    description: feed player
    usage: /feed

  heal:
    description: heal player
    usage: /heal

  getkit:
    description: kit
    usage: /getkit

  warden:
    description: start warden chase game
    usage: /warden

  earape:
    description: earape player
    usage: /earape

permissions:
  ranks.admin:
    description: "admin"
    children: [ranks.mod, ranks.jrmod] #idk if it inerhits children from lower children, if so you can remove ranks.jrmod
  ranks.mod:
    description: "mod"
    children: [ranks.jrmod]
  ranks.jrmod:
    description: "jrmod"